database:
  type: "sqlite"
  connection_string: "insight.db"
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "insight"
models_dir: "models"
models_langs:
  zh: "zh_my"
  en: "en_my"
  xx: "xx_my"
